; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Sat Mar 16 2019 23:24:38 GMT+0100 (Mitteleuropäische Normalzeit)

