; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Sat Mar 16 2019 23:24:38 GMT+0100 (Mitteleuropäische Normalzeit)
; Wait for set temperatures to be reached
M116 P0

